// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEXr0LbXaqghfG8MTmCmkAoZsziyKhW0s',
    appId: '1:1041118896633:web:ddae62da336f42bc60dd28',
    messagingSenderId: '1041118896633',
    projectId: 'handasa-rides',
    authDomain: 'handasa-rides.firebaseapp.com',
    storageBucket: 'handasa-rides.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl46LnpCS3npxr8_z4QTwgI6G3rER7KOo',
    appId: '1:1041118896633:android:076a8fecb55f5afd60dd28',
    messagingSenderId: '1041118896633',
    projectId: 'handasa-rides',
    storageBucket: 'handasa-rides.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmA1IjlcqFu2Njs6UmWihoK6Rxo7AgZFM',
    appId: '1:1041118896633:ios:92472f09befd51c460dd28',
    messagingSenderId: '1041118896633',
    projectId: 'handasa-rides',
    storageBucket: 'handasa-rides.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmA1IjlcqFu2Njs6UmWihoK6Rxo7AgZFM',
    appId: '1:1041118896633:ios:85fe98339f1e7a9560dd28',
    messagingSenderId: '1041118896633',
    projectId: 'handasa-rides',
    storageBucket: 'handasa-rides.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
